"""Fixed response text. Corrections are templated, never generated by a model."""

URGENT_CARE = (
    "If you have these symptoms now, please seek urgent medical care or call your local "
    "emergency number right away."
)
HEDGE = (
    "This is general information, not a diagnosis. Please have a clinician assess your situation."
)
BLOCK_FALLBACK = (
    "I can't share that answer safely. Please speak with a doctor or pharmacist about this "
    "question. If you think this is an emergency, call your local emergency number."
)
ESCALATE_HOLD = (
    "This response is being reviewed by a clinician before it is shared. If this is an "
    "emergency, call your local emergency number now."
)
APPENDS = {"urgent_care": URGENT_CARE, "hedge": HEDGE}
